- name: Deploy Dockerized Node.js App
  hosts: web
  vars:
    private_key: "{{ lookup('env','EC2_KEY') }}"
  tasks:
    - name: Pull latest image
      shell: docker pull diyacapg/myapp:latest

    - name: Stop running container if any
      shell: docker rm -f myapp || true

    - name: Run new container
      shell: docker run -d --name myapp -p 80:3000 diyacapg/myapp:latest
